apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s29e7lj9r-go
  janus-idp.io/tekton: s29e7lj9r-go
  backstage.io/kubernetes-id: s29e7lj9r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s29e7lj9r-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
